#!/usr/bin/env python
import os
from importlib import import_module
import rospy
from mas_perception_libs import RecognizeImageService


if __name__ == '__main__':
    rospy.init_node('~image_recognition_server')
    service_name = rospy.get_param('~service_name', '~recognize_image')
    model_directory = rospy.get_param('~model_directory', '')
    if not model_directory:
        from rospkg import ResourceNotFound, RosPack
        try:
            rp = RosPack()
            model_directory = os.path.join(rp.get_path('mas_perception_libs'), 'models')
        except ResourceNotFound as e:
            rospy.logerr(e.message)
            raise

    recog_module = rospy.get_param('~recognition_module', 'mas_perception_libs')
    recog_class_name = rospy.get_param('~recognition_class', 'ImageClassifierTest')
    recog_class = getattr(import_module(recog_module), recog_class_name)
    RecognizeImageService(recog_class, model_directory, service_name)
    rospy.spin()
