#!/usr/bin/env python
import rospy
from mas_perception_libs import SceneDetectionActionServerTest


if __name__ == "__main__":
    rospy.init_node('object_detection_test_server')
    _ = SceneDetectionActionServerTest(rospy.get_name())
    rospy.spin()
